---
title: "Mega Millions Data Exploration in R"
output: jupyter_notebook
---
```{r}
```


```{r}
library(tidyr)
library(gridExtra)
library(dplyr)
library(datasets)
library(ggplot2)
library(Ecdat)
#import dataset
WinningNumbers <- read.csv("Lottery_Mega_Millions_Winning_Numbers__Beginning_2002_Wrangled.csv")
View(WinningNumbers)
Wins <- read.csv("jackpot winners.csv")
View(Wins)
names(Wins)[names(Wins) == "amount..won"] <- "Jackpot"
```


```{r}
Women = data.frame(Wins %>% filter(gender == "F"))
View(Women)

Men = data.frame(Wins %>% filter(gender == "M"))
View(Men)

MixedGroups = data.frame(Wins %>% filter(gender == "Mixed"))
View(Groups)

Unknown = data.frame(Wins %>% filter(gender %in% c ("Unk", "Mixed")))
View(Unknown)

SingleSex = data.frame(Wins %>% filter(gender %in% c ("M", "F")))
View(SingleSex)

FWins<-Women$Jackpot
MWins<-Men$Jackpot
GWins<-MixedGroups$Jackpot
UWins<-Unknown$Jackpot
SWins<-SingleSex$Jackpot

mean(FWins)
# 93696552
mean(MWins)
#107261728
mean(GWins)
#105291045
mean(UWins)
# 264166372
mean(SWins)
# 103685455
```


```{r}
# t-test to see if  Women's Jackpots were significantly different than Men's.
t_dep <- t.test(FWins, MWins, paired =FALSE)
t_dep
```


```{r}
```


```{r}
# t-test to see if Jackpots for Individual Winners and Single Sex Groups were significantly different than Jackpots for Mixed Groups and Winners where the Sex/Gender was unknown.
t2 <- t.test(SWins, UWins, paired =FALSE)
t2
```

```{r}
# t-test to see if Jackpots for Individual Winners and Single Sex Groups were significantly different than Jackpots for Mixed Groups 
t3 <- t.test(SWins, GWins, paired =FALSE)
t3
```


```{r}
# Which state has won the most 
# use aggregate() function to find mean jackpot amount by state
CashByState <- aggregate(Jackpot~state, Wins, sum)
View(CashByState)
# South Carolina has won the most prize money 
ggplot(CashByState, aes(y = Jackpot, x = state)) + geom_point() + geom_smooth(method='lm', se = TRUE) + ggtitle("Total Jackpot winnings by State")+ ylab("Total Jackpot Winnings") + xlab("State")
```


```{r}
# did the jackpots change over time?
# use aggregate() function to find mean jackpot amount by year
CashByYear <- aggregate(Jackpot~year, WinningNumbers, sum)
View(CashByYear)
ggplot(CashByYear, aes(y = Jackpot, x = year)) + geom_point() + geom_smooth(method='lm', se = FALSE) + ggtitle("Total Jackpot winnings over Time")+ ylab("Total Jackpot Winnings") + xlab("Time")
```


```{r}
CashByGender <- aggregate(Jackpot~gender, Wins, sum)
View(CashByGender)
```


```{r}
```


